version: "3.0"
services:

  app:
    labels:
      - "traefik.enable=true"
      ### ==== to https ====
      - "traefik.http.routers.radicale-secure.entrypoints=websecure"
      - "traefik.http.routers.radicale-secure.rule=Host(`$HOSTNAME0.$DOMAINNAME`)"
      - "traefik.http.routers.radicale-secure.tls=true"
      - "traefik.http.routers.radicale-secure.tls.certresolver=production"  # für eigene Zertifikate
      ### ==== to service ====
      - "traefik.http.routers.radicale-secure.service=radicale"
      - "traefik.http.services.radicale.loadbalancer.server.port=$PORT"
      - "traefik.docker.network=proxy"
      ### ==== redirect to authelia for secure login ====
      - "traefik.http.routers.radicale-secure.middlewares=rate-limit@file,secHeaders@file"
    networks:
      - proxy

networks:
  proxy:
    external: true

